### ISSUE TITLE
Issue with newer Chromium based browsers

### ISSUE THREAD

**Issue by jasonmacer** [Pauan/tab-organizer#183]
I don't know if this project is even being updated anymore, but I am slowly migrating over to Brave Browser and wanted to take this extension with me, however each time I try to pull up the extension it crashes the browser.

If the project has now been abandoned I know nothing will get done, but if not I'm more than willing to assist with additional details on this issue.

**Comment by mikhoul** [comment]
I use  Brave also and I migrated to https://chrome.google.com/webstore/detail/cluster-window-tab-manage/aadahadfdmiibmdhfmpbeeebejmjnkef which is lot more powerful IMO to manage tabs and windows.

Regards :octocat:

**Comment by Pauan** [comment]
@jasonmacer I've been slowly continuing work on the [rust branch](https://github.com/Pauan/tab-organizer/tree/rust), but it's for Firefox only, because Chrome is missing important APIs.

If it is causing the entire browser to crash, then that's a bug in Brave, and there's nothing I can do about that. It's supposed to be impossible for extensions to crash the browser (that's why they're isolated in separate processes).

----

@mikhoul I personally prefer the sidebar style, but that's a very nice extension for giving a big wide view of all your tabs. I'm glad you found something which works for you!

**Comment by jasonmacer** [comment]
> I use Brave also and I migrated to https://chrome.google.com/webstore/detail/cluster-window-tab-manage/aadahadfdmiibmdhfmpbeeebejmjnkef which is lot more powerful IMO to manage tabs and windows.
> 
> Regards :octocat:

Thanks for the response @mikhoul and @Pauan I did actually just download the product that @mikhoul  recommended. Thanks again!  

Also, @Pauan it was an issue inside Brave. I completely removed the install then started from scratch with a fresh go, and the issue was solved. I'm guessing it was an  update or something that they pushed.  

Who knows.
